### ISSUE TITLE
SyntaxError : invalid syntax 

### ISSUE THREAD

**Issue by CrashBanditCoin** [pysrc/cvauto#1]
Hi ! Is it normal this error ? 
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from cvauto.position import KeyType
  File "/home/me/Documents/auto/cvauto/cvauto/position.py", line 8
    def __init__(self, src: str, dx=None, dy=None):
                          ^
SyntaxError: invalid syntax
```

**Comment by pysrc** [comment]
Is python version too low ?
